"""
用于github Action的CI/CD
"""

name:


on:
  push:
   tags:
     - '*'


jobs:
  build-publish:
    name:
    runs-on:
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version:"3.10"

      - name:
      - run:

      - name:
      - run:
